### PR TITLE
collectives intro: add Scan to team-based list

### PR DESCRIPTION
**Pull request by davidozog**
## Summary of changes
This is a doc-edit that addresses https://github.com/openshmem-org/specification/issues/544

## Proposal Checklist
- [X] Link to issue(s)
- [X] Changelog entry
- [X] Reviewed for changes to front matter
- [X] Reviewed for changes to back matter

### CODE REVIEW

**Review by maawad — APPROVED** [review]
Looks good.

**Comment by davidozog** [comment]
@kwaters4 @isubsmith @BKP - I'm looking for one more approval here if possible.  This addition should be fairly straightforward.

**Review by lstewart — APPROVED** [review]
Looks fine.
I do find it interesting that the intro section mentions the typed functions but not the C11 or C++ versions.

**Comment by isubsmith** [comment]
sorry for the delay. buried in stuff. this looks fine to me though.

**Pull request merged**
